# Generated by Django 3.1.4 on 2021-01-05 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KalendarzPs',
            fields=[
                ('id_konkursu', models.AutoField(primary_key=True, serialize=False)),
                ('typ_konkursu', models.CharField(max_length=45)),
                ('data', models.DateField()),
                ('liczba_uczestnikow_kwali', models.IntegerField()),
            ],
            options={
                'db_table': 'kalendarz_ps',
            },
        ),
        migrations.CreateModel(
            name='Sedziowie',
            fields=[
                ('id_sedziego', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'sedziowie',
            },
        ),
        migrations.CreateModel(
            name='Skocznie',
            fields=[
                ('id_skoczni', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('kraj', models.CharField(max_length=45)),
                ('miasto', models.CharField(max_length=45)),
                ('nazwa', models.CharField(max_length=45, unique=True)),
                ('punkt_k', models.FloatField()),
                ('punkt_hs', models.FloatField()),
            ],
            options={
                'db_table': 'skocznie',
            },
        ),
        migrations.CreateModel(
            name='Zawodnicy',
            fields=[
                ('id_zawodnika', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('narodowosc', models.CharField(max_length=45)),
                ('data_urodzenia', models.DateField()),
                ('ilosc_punktow', models.FloatField()),
                ('miejsce', models.IntegerField()),
                ('straty_punktowe', models.FloatField()),
            ],
            options={
                'db_table': 'zawodnicy',
            },
        ),
        migrations.CreateModel(
            name='Wyniki',
            fields=[
                ('id_wyniku', models.AutoField(primary_key=True, serialize=False)),
                ('kwalifikacje', models.FloatField()),
                ('czy_zakwalifikowany_do_1', models.CharField(max_length=45)),
                ('number_1_odleglosc', models.FloatField(db_column='1_odleglosc')),
                ('number_1_punkty', models.FloatField(db_column='1_punkty')),
                ('czy_zakwalifikowany_do_2', models.CharField(max_length=45)),
                ('number_2_odleglosc', models.FloatField(db_column='2_odleglosc')),
                ('number_2_punkty', models.FloatField(db_column='2_punkty')),
                ('wynik', models.FloatField()),
                ('miejsce', models.IntegerField()),
                ('id_konkursu', models.ForeignKey(db_column='id_konkursu', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.kalendarzps')),
                ('id_zawodnika', models.ForeignKey(db_column='id_zawodnika', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.zawodnicy')),
            ],
            options={
                'db_table': 'wyniki',
            },
        ),
        migrations.CreateModel(
            name='Oceny',
            fields=[
                ('id_oceny', models.AutoField(primary_key=True, serialize=False)),
                ('ocena', models.FloatField()),
                ('id_sedziego', models.ForeignKey(db_column='id_sedziego', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.sedziowie')),
                ('id_wyniku', models.ForeignKey(db_column='id_wyniku', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.wyniki')),
                ('id_zawodnika', models.ForeignKey(db_column='id_zawodnika', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.zawodnicy')),
            ],
            options={
                'db_table': 'oceny',
            },
        ),
        migrations.AddField(
            model_name='kalendarzps',
            name='id_skoczni',
            field=models.ForeignKey(db_column='id_skoczni', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.skocznie'),
        ),
    ]
