# Generated by Django 3.1.4 on 2021-01-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kalendarzps',
            options={'verbose_name': 'Kalendarz PS', 'verbose_name_plural': 'Kalendarze PS'},
        ),
        migrations.AlterModelOptions(
            name='skocznie',
            options={'verbose_name': 'Skocznia', 'verbose_name_plural': 'Skocznie'},
        ),
    ]
